[project]
name = "dz-catalog-analysis-aleksashin-m26-555"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Pavel Aleksashin", email = "aleksashin.pavel@inbox.ru" }
]
requires-python = ">=3.12"
dependencies = []

[project.scripts]
dz-catalog-analysis-aleksashin-m26-555 = "dz_catalog_analysis_aleksashin_m26_555:main"

[build-system]
requires = ["uv_build>=0.12.19,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "ruff>=0.16.9",
]

[tool.ruff]
line-length = 88
target-version = "py312"
exclude = ["venv", ".venv", "dist", "__pycache__"]

[tool.ruff.lint]
select = ["E", "F", "I"]
ignore = [] 